### DISCUSSION TITLE
truncated codeblock

### DISCUSSION THREAD

**Discussion by DanRoscigno** [signcl/docusaurus-prince-pdf#55] [Q&A] [answered]
I am seeing that code blocks that extend beyond the bottom of a page in the PDF are truncated. Is there something that I can do to cause the code block to be continued on the next page of the PDF?

The output is really beautiful, thanks so much for docusaurus-prince-pdf!

**Comment by kamilogorek** [comment, marked as answer]
You can work around this by adding this CSS snippet directly to your docusaurus page

```css
/* This works around the issue of truncated code-blocks in https://github.com/signcl/docusaurus-prince-pdf/ */
@media print {
  code[class*='codeBlockLines'] {
    float: none;
    display: block;
  }
}
```
